#######################################################
# 
# CovgCollValidator.py
# Python implementation of the Class CovgCollValidator
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 15:49:51
# Original author: Bug
# 
#######################################################

class CovgCollValidator():
    def __init__(self, covg_coll_nodes):
        self.m_covg_coll_nodes = covg_coll_nodes

    def validate_json(self):
        print("Not implemented")
