#######################################################
# 
# CovgValidator.py
# Python implementation of the Class CovgValidator
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 15:50:36
# Original author: Bug
# 
#######################################################
import jsonschema

class CovgValidator():
    """Has enum of expected nodes, and link to sub-schema
    """
    def __init__(self, covg_nodes):
        self.m_covg_nodes = covg_nodes
        #TODO make this OS independent
        self.m_schema_dir = '..\..\schema'

    def validate_json(self, covg_dict):
        schema_file = 'sss'