#######################################################
# 
# DomainNodes.py
# Python implementation of the Enumeration DomainNodes
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 12:41:38
# Original author: Bug
# 
#######################################################


class DomainNodes:
    """Objects found within the Domain object.
    """

    type = "Domain"