#######################################################
# 
# DomainValidator.py
# Python implementation of the Class DomainValidator
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 12:41:38
# Original author: Bug
# 
#######################################################
from ValidationDesign.Validator import Validator
from ValidationDesign.DomainNodes import DomainNodes

class DomainValidator(Validator):
    m_DomainNodes= DomainNodes()




    def validate_json_part():
        pass