#######################################################
# 
# ParametersNodes.py
# Python implementation of the Enumeration ParametersNodes
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 12:41:38
# Original author: Bug
# 
#######################################################


class ParametersNodes:
    """Objects within the Parameters object.
    """
    pass