#######################################################
# 
# ParamValidator.py
# Python implementation of the Class ParamValidator
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 12:41:38
# Original author: Bug
# 
#######################################################
from ValidationDesign.Validator import Validator
from ValidationDesign.ParametersNodes import ParametersNodes

class ParamValidator(Validator):
    m_ParametersNodes= ParametersNodes()




    def validate_json_part():
        pass