#######################################################
# 
# Validator.py
# Python implementation of the Class Validator
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 12:41:38
# Original author: Bug
# 
#######################################################


class Validator:
    def validate_json_part():
        pass
    m_RangesNodes= RangesNodes()



