#######################################################
# 
# CovgValidator.py
# Python implementation of the Class CovgValidator
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 15:50:36
# Original author: Jane Lewis
# 
#######################################################
import jsonschema
import os
from JSONCheck import enum, loadfile


class CovgValidator():
    """Has enum of expected nodes, and link to sub-schema
    """
    def __init__(self):
        self.m_covg_nodes = enum(domain="domain", params="parameters",
                                 ranges="ranges", range_alt="rangeAlternates")
        self.m_schema_dir = '..' + os.pathsep + 'schemas'

    def validate_json(self, covg_dict):
        # Divide up object into parts according to nodes
        # pass relevant part to sub-validator
        schema_file = 'sss'