#######################################################
# 
# CovgValidator.py
# Python implementation of the Class CovgValidator
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 15:50:36
# Original author: Jane Lewis
# 
#######################################################
import jsonschema
from JSONCheck import enum

class CovgValidator():
    """Has enum of expected nodes, and link to sub-schema
    """
    def __init__(self):
        self.m_covg_nodes = enum(domain="domain", params="parameters",
                                 ranges="ranges", range_alt="rangeAlternates")
        #TODO make this OS independent
        self.m_schema_dir = '..\..\schema'

    def validate_json(self, covg_dict):
        schema_file = 'sss'