#######################################################
# 
# CovgCollValidator.py
# Python implementation of the Class CovgCollValidator
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 15:49:51
# Original author: Jane Lewis
# 
#######################################################

from JSONCheck import enum

class CovgCollValidator():
    def __init__(self, covg_coll_nodes):
        self.m_covg_coll_nodes = enum(domain="domainType", params="parameters",
                                      the_ref="referencing", covgs="coverages")

    def validate_json(self):
        print("Not implemented")
