#######################################################
# 
# CovgNodes.py
# Python implementation of the Enumeration CovgNodes
# Generated by Enterprise Architect
# Created on:      25-Oct-2016 12:41:38
# Original author: Jane Lewis
# 
#######################################################


class CovgNodes:
    """Parent CoverageJSON object nodes.
    """

    type = "Coverage"